package com.neuedu.ssm_douban_movie.entity;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_id
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_name
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.rate
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.director
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.screenwriter
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String screenwriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.actor
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.type
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.area
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.language
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.length
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.imgurl
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.star
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String star;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_id
     *
     * @return the value of movie.m_id
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_id
     *
     * @param mId the value for movie.m_id
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setmId(String mId) {
        this.mId = mId == null ? null : mId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_name
     *
     * @return the value of movie.m_name
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_name
     *
     * @param mName the value for movie.m_name
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.rate
     *
     * @return the value of movie.rate
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.rate
     *
     * @param rate the value for movie.rate
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.director
     *
     * @return the value of movie.director
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.director
     *
     * @param director the value for movie.director
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.screenwriter
     *
     * @return the value of movie.screenwriter
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getScreenwriter() {
        return screenwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.screenwriter
     *
     * @param screenwriter the value for movie.screenwriter
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setScreenwriter(String screenwriter) {
        this.screenwriter = screenwriter == null ? null : screenwriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.actor
     *
     * @return the value of movie.actor
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.actor
     *
     * @param actor the value for movie.actor
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.type
     *
     * @return the value of movie.type
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.type
     *
     * @param type the value for movie.type
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.area
     *
     * @return the value of movie.area
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.area
     *
     * @param area the value for movie.area
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.language
     *
     * @return the value of movie.language
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.language
     *
     * @param language the value for movie.language
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.length
     *
     * @return the value of movie.length
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.length
     *
     * @param length the value for movie.length
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.imgurl
     *
     * @return the value of movie.imgurl
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.imgurl
     *
     * @param imgurl the value for movie.imgurl
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.star
     *
     * @return the value of movie.star
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.star
     *
     * @param star the value for movie.star
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setStar(String star) {
        this.star = star == null ? null : star.trim();
    }
}