package com.neuedu.ssm_douban_movie.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_passwd
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    private String uPasswd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_passwd
     *
     * @return the value of user.u_passwd
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public String getuPasswd() {
        return uPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_passwd
     *
     * @param uPasswd the value for user.u_passwd
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    public void setuPasswd(String uPasswd) {
        this.uPasswd = uPasswd == null ? null : uPasswd.trim();
    }
}