package com.neuedu.ssm_douban_movie.mapper;

import com.neuedu.ssm_douban_movie.entity.Movie;
import com.neuedu.ssm_douban_movie.entity.MovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    long countByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int deleteByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int deleteByPrimaryKey(String mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int insertSelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    List<Movie> selectByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    Movie selectByPrimaryKey(String mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int updateByExample(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbg.generated Tue Aug 13 13:43:36 CST 2019
     */
    int updateByPrimaryKey(Movie record);
}